import textwrap
from datetime import datetime
from typing import List
from pathlib import Path

from chimera_nexus.core.domain import HybridThreatChain, HybridNode, RelationType, ThreatDomain
from chimera_nexus.analysis.auditor import AuditFinding

class ReportEngine:
    """
    Generates decision-support artifacts.
    Adheres to the principle: 'Explainable over Powerful'.
    """

    def generate_graphviz_dot(self, chain: HybridThreatChain) -> str:
        """
        Generates a standard Graphviz DOT string.
        Visualizes the topology of the threat chain.
        """
        lines = ["digraph HybridThreatChain {"]
        lines.append('  rankdir="LR";') # Left-to-Right flow
        lines.append('  node [fontname="Helvetica", shape="box", style="filled"];')
        lines.append('  edge [fontname="Helvetica", fontsize=10];')
        
        # Domain Colors (Muted, professional palette)
        domain_colors = {
            ThreatDomain.CYBER: "#d1e7dd",       # Light Green
            ThreatDomain.INFORMATION: "#fff3cd", # Light Yellow
            ThreatDomain.ECONOMIC: "#f8d7da",    # Light Red
            ThreatDomain.POLITICAL: "#e2e3e5",   # Grey
            ThreatDomain.SOCIAL: "#d1ecf1",      # Light Cyan
            ThreatDomain.PHYSICAL: "#cff4fc",
            ThreatDomain.PSYCHOLOGICAL: "#f1d1f1"
        }

        # 1. Nodes
        for node in chain.nodes.values():
            color = domain_colors.get(node.domain, "#ffffff")
            # Visual cue for confidence: Line width
            penwidth = "3.0" if node.confidence > 0.8 else "1.0"
            
            # Label formatting
            label = f"<{node.signal_type.upper()}<BR/>" \
                    f"<FONT POINT-SIZE='10'>{node.domain.value}</FONT><BR/>" \
                    f"<FONT POINT-SIZE='9'>Conf: {node.confidence}</FONT>>"
            
            lines.append(
                f'  "{node.id}" [label={label}, fillcolor="{color}", penwidth="{penwidth}"];'
            )

        # 2. Edges
        for edge in chain.edges:
            style = "solid"
            if edge.relation_type == RelationType.CORRELATION:
                style = "dashed"
            
            # Label edges with justification if weight is high
            label = edge.relation_type.value
            if edge.weight > 0.8:
                label += f"\\n(High Conf)"
            
            lines.append(
                f'  "{edge.source_id}" -> "{edge.target_id}" [label="{label}", style="{style}"];'
            )

        lines.append("}")
        return "\n".join(lines)

    def generate_markdown_report(self, chain: HybridThreatChain, findings: List[AuditFinding]) -> str:
        """
        Generates a read-only Executive Briefing.
        """
        iap = chain.calculate_iap(urgency=5.0)
        ccs = chain.coherence_score
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Color-coded risk text for Markdown
        risk_label = "**CRITICAL**" if iap > 7.0 else "**HIGH**" if iap > 4.0 else "MODERATE"

        md = f"""# CHIMERA NEXUS: THREAT ASSESSMENT
**Ref ID:** `{chain.id}`
**Date:** {timestamp}
**Operation Name:** {chain.name}

---

## 1. EXECUTIVE SUMMARY
| Metric | Score | Assessment |
| :--- | :--- | :--- |
| **IAP (Decision Pressure)** | `{iap:.2f}` | {risk_label} |
| **Coherence Score** | `{ccs:.2f}` | Structural Integrity |
| **Node Count** | {len(chain.nodes)} | Signals Collected |
| **Domain Mix** | {len(chain.domain_mix)} | {', '.join([d.value for d in chain.domain_mix])} |

## 2. AUDIT & BIAS CHECK
*(Automated Red Team Analysis)*
"""
        
        if not findings:
            md += "\n> ✅ **No structural cognitive biases detected.** The chain appears logically sound.\n"
        else:
            for f in findings:
                md += f"- ⚠️ **{f.bias_type.value.upper()}** (Severity: {f.severity})\n"
                md += f"  - *Issue:* {f.description}\n"
                md += f"  - *Fix:* {f.remediation_hint}\n"

        md += "\n## 3. SIGNAL CHAIN (CHRONOLOGICAL)\n"
        
        # Sort nodes by timestamp (simulated order of addition for now)
        sorted_nodes = sorted(chain.nodes.values(), key=lambda x: x.timestamp)
        
        for n in sorted_nodes:
            md += f"### {n.timestamp.strftime('%H:%M')} | [{n.domain.value.upper()}] {n.signal_type}\n"
            md += f"- **Confidence:** {n.confidence}\n"
            md += f"- **Description:** {n.description}\n\n"

        md += "---\n*Generated by CHIMERA Nexus Protocol*"
        return md